title: Instants magiques
email: instants.magiques25@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/pdf"
    values:
      pdf: true

# Build settings
markdown: kramdown
theme: minima
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - instants-magiques-bld

sass:
  sass_dir: _sass
  style: compressed